version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    hostname: dpg-cr5ir7tumphs73e4rnjg-a
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=wallet_gu3s
      - POSTGRES_USER=wallet_gu3s_user
      - POSTGRES_PASSWORD=hiNaqnJ9xOzXp3PMw88rSpDajcBs23je
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s

  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cr5ir7tumphs73e4rnjg-a:5432/wallet_gu3s
      - SPRING_DATASOURCE_USERNAME=wallet_gu3s_user
      - SPRING_DATASOURCE_PASSWORD=hiNaqnJ9xOzXp3PMw88rSpDajcBs23je
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080 || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s

