version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=wallet_v9dv
      - POSTGRES_USER=wallet_v9dv_user
      - POSTGRES_PASSWORD=GAqNaY7ew86J0SOs8JdaUVtVWUv6hyoL
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s

  webapi:
    build:
      dockerfile: webapi_docker/Dockerfile
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/wallet_v9dv
      - SPRING_DATASOURCE_USERNAME=wallet_v9dv_user
      - SPRING_DATASOURCE_PASSWORD=GAqNaY7ew86J0SOs8JdaUVtVWUv6hyoL
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080 || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s

networks:
  app-network:
    driver: bridge
