version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=wallet_v9dv
      - POSTGRES_USER=wallet_v9dv_user
      - POSTGRES_PASSWORD=GAqNaY7ew86J0SOs8JdaUVtVWUv6hyoL
    ports:
      - "5432:5432"
    networks:
      - app-network

  webapi:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/wallet_v9dv
      - SPRING_DATASOURCE_USERNAME=wallet_v9dv_user
      - SPRING_DATASOURCE_PASSWORD=GAqNaY7ew86J0SOs8JdaUVtVWUv6hyoL
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
