server:
    port: 8080

jwt:
    secret: r1Wq3Y7Ql8ivrpC4A6vEgBg1kllCKCrFkwhbZUNZ6Y8=
    lifetime: 24h

spring:
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    datasource:
        # По умолчанию postgresql имеет 5432 порт. Но так как подразумевается запуск через docker-compose, указан порт
        # из docker-compose.yaml для корректной проброски. Если у вас локально установлен postgresql и вы собираетесь
        # использовать его, то требуется поменить его на нужный
        url: jdbc:jdbc:postgresql://dpg-cqfpp1pu0jms7386bqbg-a:5432/wallet_v9dv
        username: wallet_v9dv_user
        password: GAqNaY7ew86J0SOs8JdaUVtVWUv6hyoL
    flyway:
        enabled: true
        locations:
          - db.migration

springdoc:
    swagger-ui:
        enabled: true