ALTER TABLE "user"
    ADD birth_date date;

ALTER TABLE "user"
    ADD created_at time WITHOUT TIME ZONE;

ALTER TABLE "user"
    ADD first_name VARCHAR(50);

ALTER TABLE "user"
    ADD last_name VARCHAR(50);

ALTER TABLE "user"
    ADD middle_name VARCHAR(50) DEFAULT 'NULL::character varying';

ALTER TABLE "user"
    ADD phone_number VARCHAR(11);

ALTER TABLE "user"
    ADD updated_at time WITHOUT TIME ZONE;

ALTER TABLE "user"
    ALTER COLUMN birth_date SET NOT NULL;

ALTER TABLE "user"
    ALTER COLUMN created_at SET NOT NULL;

ALTER TABLE "user"
    ALTER COLUMN first_name SET NOT NULL;

ALTER TABLE "user"
    ALTER COLUMN last_name SET NOT NULL;

ALTER TABLE "user"
    ALTER COLUMN phone_number SET NOT NULL;

ALTER TABLE "user"
    ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE "user"
    DROP COLUMN birthdate;

ALTER TABLE "user"
    DROP COLUMN createdat;

ALTER TABLE "user"
    DROP COLUMN firstname;

ALTER TABLE "user"
    DROP COLUMN lastname;

ALTER TABLE "user"
    DROP COLUMN middlename;

ALTER TABLE "user"
    DROP COLUMN phonenumber;

ALTER TABLE "user"
    DROP COLUMN updatedat;

ALTER TABLE "user"
    DROP COLUMN id;

ALTER TABLE "user"
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

CREATE SEQUENCE IF NOT EXISTS user_id_seq;
ALTER TABLE "user"
    ALTER COLUMN id SET NOT NULL;
ALTER TABLE "user"
    ALTER COLUMN id SET DEFAULT nextval('user_id_seq');

ALTER SEQUENCE user_id_seq OWNED BY "user".id;

ALTER TABLE "user"
    ALTER COLUMN password SET NOT NULL;